### PR TITLE
Allows user to view all artists

### LINKED ISSUE #23: Viewing all artists
as an unauthenticated user
when I visit "/artists"
I expect to see a list of all artists in alphabetical order

### PR DESCRIPTION
**Pull request by julsfelic**
Added a link in the navigation to allow any user (guest or registered)
to navigate to the artists page. Created the model along with associated
controller and views for an artist.

@Draganovic @Salvi6God @scottfirestone Check out the code and let 
me know if you see anything that needs explaining or could use refactoring.

Closes #23

### CODE REVIEW

**Comment by ghost** [comment]
@julsfelic Yo! I checked out the code and noticed that you added a link on the navigation bar that allows any user to visit an artists index! I also checked your tests and they are good enough for me :+1: !

**Comment by ghost** [comment]
Actually, I saw a mistake dude! The styling within the Artist page isn't within a container plus, we haven't connected the artists with the albums yet... Either way,  it's good that it's still a WIP branch and that we haven't merged yet !

**Comment by julsfelic** [comment]
Alright. All good now! We'll handle the association between albums and artists when we tackle the artist show page

**Comment by scottfirestone** [comment]
Looks good. Merging...

**Pull request merged**
